{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "workflow-engine.fullname" . }}-secrets
  labels:
    {{- include "workflow-engine.labels" . | nindent 4 }}
type: Opaque
stringData:
  # Database Password
  DB_PASSWORD: {{ .Values.secrets.database.password | quote }}
  
  # Keycloak Client Secret
  KEYCLOAK_CLIENT_SECRET: {{ .Values.secrets.keycloak.clientSecret | quote }}
{{- end }}
